name: cs11
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  # UI
  google_fonts: ^8.0.1
  flutter_animate: ^4.5.0
  # State & Logic
  provider: ^6.1.1
  # Database & Security
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^10.0.0
  encrypt: ^5.0.3
  # Hardware Sensors
  device_info_plus: ^12.3.0
  disk_space_2: ^1.0.12
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  url_launcher: ^6.3.2
  percent_indicator: ^4.2.5
  http: ^1.6.0
  dart_rss: ^3.0.3
  file_picker: ^10.3.10
  path_provider: ^2.1.5
  open_file: ^3.5.11
  path: ^1.9.1
  xml: ^6.6.1
  battery_info: ^1.1.1
  safe_device: ^1.3.8
  carrier_info: ^2.0.8

  # --- HARDWARE & SENSORS (FIXED VERSIONS) ---
  connectivity_plus: ^6.0.3
  sensors_plus: ^5.0.1
  vibration: ^3.1.6
  local_auth: ^2.2.0
  camera: ^0.10.5
  battery_plus: ^6.0.1
  audioplayers: ^6.0.0
  record: ^5.1.0
  screen_brightness: ^0.2.2
  flutter_volume_controller: ^1.3.3
  permission_handler: ^11.3.0
  proximity_sensor: ^1.2.0
  light_sensor: ^3.0.2
  audio_session: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/test_beep.mp3

dependency_overrides:
  record_linux: ^1.2.0

